#!/bin/sh
# /etc/hotplug.d/usb/21-modem_detect

case "$ACTION" in
    add)
        case "$PRODUCT" in
            # Dell modems
            413c/81d7/*|413c/81d9/*)
                logger "Dell modem detected: $PRODUCT"
                if [ -f /etc/init.d/modemmanager ]; then
                    (sleep 5; /etc/init.d/modemmanager restart) &
                else
                    logger "ERROR: modemmanager not restart"
                fi
                ;;
            # Tw 5G modems  
            1e2d/00b3/*|1e2d/00b7/*)
                logger "Tw 5G modem detected: $PRODUCT"
                if [ -f /etc/init.d/modemmanager ]; then
                    (sleep 5; /etc/init.d/modemmanager restart) &
                else
                    logger "ERROR: modemmanager nof restart"
                fi
                ;;
            # Other modems  
            12d1/15c1/*|2cb7/0007/*)
                logger "Other modem detected: $PRODUCT"
                (sleep 5; 
                 logger "Configuring mm interface and save & apply";
                 ifdown mm 2>/dev/null;
                 uci commit network;
                 /etc/init.d/network reload;
                 sleep 2;
                 ifup mm;
                 logger "MM interface restart and apply") &
                ;;
        esac
        ;;
    remove)
        case "$PRODUCT" in
            413c/81d7/*|413c/81d9/*|1e2d/00b3/*|1e2d/00b7/*|12d1/15c1/*|2cb7/0007/*)
                logger "Modem removed: $PRODUCT"
                ;;
        esac
        ;;
esac