#!/bin/sh
# /etc/hotplug.d/usb/23-modem-detect

is_supported_modem() {
    case "$PRODUCT" in
        413c/81d7/*|413c/81d9/*|1e2d/00b3/*|1e2d/00b7/*|12d1/15c1/*|2cb7/0007/*|0489/e0b4/*)
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

restart_modemmanager() {
    if [ -f /etc/init.d/modemmanager ]; then
        logger "Restarting modemmanager for modem: $PRODUCT"
        /etc/init.d/modemmanager restart
        return $?
    else
        logger "ERROR: modemmanager init script not found"
        return 1
    fi
}

restart_interface() {
    logger "Restarting interface mm"
    ifdown mm 2>/dev/null
    sleep 2
    ifup mm
}

case "$ACTION" in
    add)
        if is_supported_modem; then
            logger "Modem detected: $PRODUCT"
            (
                restart_modemmanager && \
                sleep 4 && \
                restart_interface
            ) &
        fi
        ;;
    remove)
        if is_supported_modem; then
            logger "Modem removed: $PRODUCT"
            ifdown mm 2>/dev/null
        fi
        ;;
esac