#!/bin/sh
#
# Hotplug Skrip ini digunakan untuk mengonfigurasi module Wi-Fi pada HAT OPIZ
# Fungsi utamanya adalah mengonfigurasi path USB pada OpenWrt yang tertukar saat menyalakan atau reboot (restart) device.
#
# Support Device:
#  * RTL8188CUS
#  * RTL8188EUS
#  * RTL8192EU
#  * RTL8192FU
#
# @lionware <lionware@siltesa.com>
# Februari 2025
#
# Distribusi dan penggunaan kode ini diperbolehkan digunakan di perangkat manapun dan dapat dimodifikasi, 
# tetapi tanpa jaminan kode ini berjalan dengan baik di perangkat tersebut :v
#
# Wi-Fi HAT (USB Wi-Fi)
#

# Periksa apakah model adalah OrangePi Zero3
model=$(cat /proc/device-tree/model 2>/dev/null | tr -d '\0')
if [[ ! "$model" =~ "OrangePi Zero3" ]]; then
    logger -t usb_wifi_hat "Skipping Wi-Fi HAT configuration - not OrangePi Zero3"
    exit 0
fi

#Debug USB
logger -t usb_debug_wlan "ACTION: $ACTION, PRODUCT: $PRODUCT"
#
# Periksa apakah ACTION == "add" atau "bind" dan dengan Vendor ID 0bda atau 2357
if [[ "$ACTION" == "add" || "$ACTION" == "bind" ]] && \
   [[ "$(echo $PRODUCT | cut -d'/' -f1)" == "bda" || "$(echo $PRODUCT | cut -d'/' -f1)" == "2357" ]] && \
   [[ "$(echo $PRODUCT | cut -d'/' -f2)" == "8179" || \
      "$(echo $PRODUCT | cut -d'/' -f2)" == "8178" || \
      "$(echo $PRODUCT | cut -d'/' -f2)" == "8176" || \
      "$(echo $PRODUCT | cut -d'/' -f2)" == "818b" || \
      "$(echo $PRODUCT | cut -d'/' -f2)" == "010c" ]]; then
      # Note: Jika ingin menambahkan VID dan terdapat angka nol (0) di depan, pastikan untuk menghapus angka nol tersebut.
      # Contoh: 0bda menjadi bda
      # VID = -f1
      # PID = -f2

    # Tampung path usb wifi dan hapus bagian /devices/
    device_path_wifi="${DEVPATH#/devices/}"
    
    # Jika path perangkat ditemukan
    if [[ -n "$device_path_wifi" ]]; then
        # Log event untuk debugging
        logger -t usb_wifi_hat "Device matched, proceeding with configuration."
        logger -t usb_wifi_hat "ACTION: $ACTION, PRODUCT: $PRODUCT"
                
        # Periksa apakah radio2 ada, jika ada maka hapus
        if uci show wireless.radio2 &>/dev/null; then
            wifi down radio2
            logger -t usb_wifi_hat "Deleting wireless radio2"
            uci -q delete wireless.radio2
            uci -q delete wireless.default_radio2
            #uci -q commit wireless
        fi
        
        # Update path USB untuk modul WIFI
        uci set wireless.radio1.path="$device_path_wifi"
        uci set wireless.default_radio1.ieee80211w="2"
        uci -q commit wireless
        wifi up radio1
        
        # Mengambil status radio1
        status_radio1=$(wifi status | awk '/"radio1":/ {flag=1} flag && /"up":/ {gsub(",", "", $2); print $2; flag=0}')
        
        # Cek apakah statusnya false, jika ya, aktifkan wifi
        if [[ "$status_radio1" == false ]]; then
            logger -t usb_wifi_hat "Setting up wireless hat"
            wifi up radio1
            echo "OK" > /tmp/wifi_up.status
        fi
    fi
fi